let allCountries = [
  ["Asia", "Afghanistan", "AF"],
  ["Europe", "Albania", "AL"],
  ["Africa", "Algeria", "AG"],
  ["Oceania", "American Samoa", "AQ"],
  ["Europe", "Andorra", "AN"],
  ["Africa", "Angola", "AO"],
  ["AmericaS", "Anguilla", "AV"],
  ["AmericaS", "Antigua and Barbuda", "AC"],
  ["AmericaS", "Argentina", "AR"],
  ["Asia", "Armenia", "AM"],
  ["AmericaS", "Aruba", "AA"],
  ["Oceania", "Australia", "AS"],
  ["Europe", "Austria", "AU"],
  ["Asia", "Azerbaijan", "AJ"],
  ["AmericaN", "Bahamas", "BF"],
  ["Asia", "Bahrain", "BA"],
  ["Asia", "Bangladesh", "BG"],
  ["AmericaS", "Barbados", "BB"],
  ["Europe", "Belarus", "BO"],
  ["Europe", "Belgium", "BE"],
  ["AmericaN", "Belize", "BH"],
  ["Africa", "Benin", "BN"],
  ["AmericaS", "Bermuda", "BD"],
  ["Asia", "Bhutan", "BT"],
  ["AmericaS", "Bolivia", "BL"],
  ["Europe", "Bosnia and Herz.", "BK"],
  ["Africa", "Botswana", "BC"],
  ["AmericaS", "Brazil", "BR"],
  ["AmericaS", "British Virgin Islands", "VI"],
  ["Asia", "Brunei", "BX"],
  ["Europe", "Bulgaria", "BU"],
  ["Africa", "Burkina Faso", "UV"],
  ["Africa", "Burundi", "BY"],
  ["Asia", "Cambodia", "CB"],
  ["Africa", "Cameroon", "CM"],
  ["AmericaN", "Canada", "CA"],
  ["Africa", "Cape Verde", "CV"],
  ["AmericaS", "Cayman Islands", "CJ"],
  ["Africa", "Central African Republic", "CT"],
  ["Africa", "Chad", "CD"],
  ["AmericaS", "Chile", "CI"],
  ["Asia", "China", "CH"],
  ["Asia", "Christmas Island", "KT"],
  ["Asia", "Cocos (Keeling) Islands", "CK"],
  ["AmericaS", "Colombia", "CO"],
  ["Africa", "Comoros", "CN"],
  ["Africa", "Central African Rep.", "CF"],
  ["Oceania", "Cook Islands", "CW"],
  ["AmericaN", "Costa Rica", "CS"],
  ["Africa", "Côte d'Ivoire", "IV"],
  ["Europe", "Croatia", "HR"],
  ["AmericaN", "Cuba", "CU"],
  ["Asia", "Cyprus", "CY"],
  ["Europe", "Czech Rep.", "EZ"],
  ["Europe", "Denmark", "DA"],
  ["Africa", "Djibouti", "DJ"],
  ["AmericaN", "Dominican Rep.", "D0"],
  ["AmericaS", "Ecuador", "EC"],
  ["Africa", "Egypt", "EG"],
  ["AmericaN", "El Salvador", "ES"],
  ["Africa", "Equatorial Guinea", "EK"],
  ["Africa", "Eritrea", "ER"],
  ["Europe", "Estonia", "EN"],
  ["Africa", "Ethiopia", "ET"],
  ["AmericaS", "Falkland Is.", "FA"],
  ["Europe", "Faroe Islands", "FO"],
  ["Oceania", "Fiji", "FJ"],
  ["Europe", "Finland", "FI"],
  ["Europe", "France", "FR"],
  ["AmericaS", "French Guiana", "FG"],
  ["Oceania", "French Polynesia", "FP"],
  ["Africa", "Gabon", "GB"],
  ["Africa", "Gambia", "GA"],
  ["Asia", "Georgia", "GG"],
  ["Europe", "Germany", "GM"],
  ["Africa", "Ghana", "GH"],
  ["Europe", "Gibraltar", "GI"],
  ["Europe", "Greece", "GR"],
  ["Antarctica", "Greenland", "GL"],
  ["AmericaS", "Grenada", "GJ"],
  ["AmericaS", "Guadeloupe", "GP"],
  ["Oceania", "Eq. Guinea", "GQ"],
  ["AmericaN", "Guatemala", "GT"],
  ["Europe", "Guernsey", "--"],
  ["Africa", "Guinea", "GV"],
  ["Africa", "Guinea-Bissau", "PU"],
  ["AmericaS", "Guyana", "GY"],
  ["AmericaN", "Haiti", "HA"],
  ["Europe", "Holy See (Vatican City)", "VT"],
  ["AmericaN", "Honduras", "HO"],
  ["Europe", "Hungary", "HU"],
  ["Europe", "Iceland", "IC"],
  ["Asia", "India", "IN"],
  ["Asia", "Indonesia", "ID"],
  ["Asia", "Iran", "IR"],
  ["Asia", "Iraq", "IZ"],
  ["Europe", "Ireland", "EI"],
  ["Asia", "Israel", "IS"],
  ["Europe", "Italy", "IT"],
  ["AmericaN", "Jamaica", "JM"],
  ["Europe", "Jan Mayen", "--"],
  ["Asia", "Japan", "JA"],
  ["Europe", "Jersey", "--"],
  ["Asia", "Jordan", "JO"],
  ["Asia", "Kazakhstan", "KZ"],
  ["Africa", "Kenya", "KE"],
  ["Oceania", "Kiribati", "KR"],
  ["Asia", "Dem. Rep. Korea", "KN"],
  ["Asia", "Korea", "KS"],
  ["Asia", "Kuwait", "KU"],
  ["Asia", "Kyrgyzstan", "KG"],
  ["Asia", "Lao PDR", "LA"],
  ["Europe", "Latvia", "LG"],
  ["Asia", "Lebanon", "LE"],
  ["Africa", "Lesotho", "LT"],
  ["Africa", "Liberia", "LI"],
  ["Africa", "Libya", "LY"],
  ["Europe", "Liechtenstein", "LS"],
  ["Europe", "Lithuania", "LH"],
  ["Europe", "Luxembourg", "LU"],
  ["Europe", "Macedonia", "MK"],
  ["Africa", "Madagascar", "MA"],
  ["Africa", "Malawi", "MI"],
  ["Asia", "Malaysia", "MY"],
  ["Asia", "Maldives", "MV"],
  ["Africa", "Mali", "ML"],
  ["Europe", "Malta", "MT"],
  ["Europe", "Man, Isle of", "--"],
  ["Oceania", "Marshall Islands", "RM"],
  ["AmericaS", "Martinique", "MB"],
  ["Africa", "Mauritania", "MR"],
  ["Africa", "Mauritius", "MP"],
  ["Africa", "Mayotte", "MF"],
  ["AmericaN", "Mexico", "MX"],
  ["Oceania", "Micronesia, Federated States of", ""],
  ["Europe", "Moldova", "MD"],
  ["Europe", "Monaco", "MN"],
  ["Asia", "Mongolia", "MG"],
  ["AmericaS", "Montserrat", "MH"],
  ["Africa", "Morocco", "MO"],
  ["Africa", "Mozamb", "MZ"],
  ["Asia", "Myanmar", "BM"],
  ["Africa", "Namibia", "WA"],
  ["Oceania", "Nauru", "NR"],
  ["Asia", "Nepal", "NP"],
  ["Europe", "Netherlands", "NL"],
  ["AmericaS", "Netherlands Antilles", "NT"],
  ["Oceania", "New Caledonia", "NC"],
  ["Oceania", "New Zealand", "NZ"],
  ["AmericaN", "Nicaragua", "NU"],
  ["Africa", "Niger", "NG"],
  ["Africa", "Nigeria", "NI"],
  ["Oceania", "Niue", "NE"],
  ["Oceania", "Norfolk Island", "NF"],
  ["Oceania", "Northern Mariana Islands", "CQ"],
  ["Europe", "Norway", "NO"],
  ["Asia", "Oman", "MU"],
  ["Asia", "Pakistan", "PK"],
  ["Oceania", "Palau", "PS"],
  ["Asia", "Palestine", "--"],
  ["AmericaN", "Panama", "PM"],
  ["Oceania", "Papua New Guinea", "PP"],
  ["AmericaS", "Paraguay", "PA"],
  ["AmericaS", "Peru", "PE"],
  ["Asia", "Philippines", "RP"],
  ["Oceania", "Pitcairn Islands", "PC"],
  ["Europe", "Poland", "PL"],
  ["Europe", "Portugal", "PO"],
  ["AmericaN", "Puerto Rico", "RQ"],
  ["Asia", "Qatar", "QA"],
  ["Africa", "Reunion", "RE"],
  ["Europe", "Romania", "RO"],
  ["Asia", "Russia", "RS"],
  ["Africa", "Rwanda", "RW"],
  ["AmericaS", "Saint Kitts and Nevis", "SC"],
  ["AmericaS", "Saint Lucia", "ST"],
  ["AmericaS", "Saint Pierre and Miquelon", "SB"],
  ["AmericaS", "Saint Vincent and the Grenadines", "VC"],
  ["Europe", "San Marino", "SM"],
  ["Africa", "Sao Tome and Principe", "TP"],
  ["Asia", "Saudi Arabia", "SA"],
  ["Africa", "Senegal", "SG"],
  ["Europe", "Montenegro", "SR"],
  ["Africa", "Seychelles", "SE"],
  ["Africa", "Sierra Leone", "SL"],
  ["Asia", "Singapore", "SN"],
  ["Europe", "Slovakia", "LO"],
  ["Europe", "Slovenia", "SI"],
  ["Oceania", "Solomon Is.", "BP"],
  ["Africa", "Somalia", "SO"],
  ["Africa", "South Africa", "SF"],
  ["Europe", "Spain", "SP"],
  ["Asia", "Sri Lanka", "CE"],
  ["Africa", "S. Sudan", "SU"],
  ["AmericaS", "Suriname", "NS"],
  ["Europe", "Svalbard", "SV"],
  ["Africa", "Swaziland", "WZ"],
  ["Europe", "Sweden", "SW"],
  ["Europe", "Switzerland", "SZ"],
  ["Asia", "Syria", "SY"],
  ["Asia", "Taiwan", "TW"],
  ["Asia", "Tajikistan", "TI"],
  ["Africa", "Tanzania", "TZ"],
  ["Asia", "Thailand", "TH"],
  ["Africa", "Togo", "TO"],
  ["Oceania", "Tokelau", "TL"],
  ["Oceania", "Tonga", "TN"],
  ["AmericaS", "Trinidad and Tobago", "TD"],
  ["Africa", "Tunisia", "TS"],
  ["Asia", "Turkey", "TU"],
  ["Asia", "Turkmenistan", "TX"],
  ["AmericaS", "Turks and Caicos Islands", "TK"],
  ["Oceania", "Tuvalu", "TV"],
  ["Africa", "Uganda", "UG"],
  ["Europe", "Ukraine", "UP"],
  ["Asia", "United Arab Emirates", "TC"],
  ["Europe", "United Kingdom", "UK"],
  ["AmericaN", "United States", "US"],
  ["AmericaS", "Uruguay", "UY"],
  ["Asia", "Uzbekistan", "UZ"],
  ["Oceania", "Vanuatu", "NH"],
  ["AmericaS", "Venezuela", "VE"],
  ["Asia", "Vietnam", "VM"],
  ["AmericaS", "Virgin Islands", "VQ"],
  ["Oceania", "Wallis and Futuna", "WF"],
  ["Africa", "Western Sahara", "WI"],
  ["Oceania", "Western Samoa", "WS"],
  ["Asia", "Yemen", "YM"],
  ["Africa", "Congo", "CG"],
  ["Africa", "Zambia", "ZA"],
  ["Africa", "Zimbabwe", "ZI"]
]

export default allCountries;